filter_settings.xbbcode:
  type: mapping
  label: 'XBBCode filter-specific settings'
  mapping:
    linebreaks:
      type: boolean
      label: 'Convert linebreaks'
    tags:
      type: string
      label: 'Tag set (optional)'

xbbcode.tag_set.*:
  type: config_entity
  label: 'XBBCode tag set'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
    tags:
      type: sequence
      label: 'Collection of tag plugins'
      sequence:
        type: mapping
        label: 'Settings for one tag plugin'
        mapping:
          id:
            type: string
            label: 'Plugin ID'
          settings:
            type: xbbcode.plugin.settings.[%parent.plugin]
            label: 'Settings'
          third_party_settings:
            type: sequence
            label: 'Third party settings'
            sequence:
              type: xbbcode.plugin.third_party.[%key]

xbbcode.tag.*:
  type: config_entity
  label: 'XBBCode tag'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
    description:
      type: text
      label: 'Description'
    name:
      type: string
      label: 'Default name'
    attached:
      type: mapping
      mapping:
        # Only the library key is supported for now.
        library:
          type: sequence
          label: 'Libraries'
          sequence:
            type: string
      label: 'Attachments'
    sample:
      type: text
      label: 'Sample code'
    template_code:
      type: string
      label: 'Inline template code'
    template_file:
      type: string
      label: 'Template file'
    settings:
      type: mapping
      label: 'Tag settings (reserved for future use)'
    third_party_settings:
      type: sequence
      label: 'Third party settings'
      sequence:
        type: xbbcode.tag_settings.third_party.[%key]
    editable:
      type: boolean
      label: 'Editable'
